const defaultstate = {

    stateExercice: [],
    stateSection: [],
    stateNatureDepense: [],
    stateTypeFinancement: [],
    stateBailleur: [],
    stateActivite: [],
    stateNatureEconomique: [],
    stateProjet: [],
     stateSousBudget: [],
    stateGrpeActivite:[],
    stateDotationNotifie: [],
    stateDotationReport: [],
    stateDotationRessourcePropre: [],
    stateDotationAutreRessource: [],
   stateGrpeActiviteBudgetNotifie:[],
    stateGrpeActiviteBudgetReport: [],
    stateGrpeActiviteBudgetRessourcePropre: [],
    stateGrpeActiviteBudgetAutreRessource: [],
    stateInformationBudget: [],
    stateBudgetEclate: [],
    stateListeBudgetEclate: [],
    stateAfficheNouvelleNature: [],
    stateEntreprise: [],
    stateBudgetViseParActivite: [],
    stateBudgetViseGroupeParActivite: [],
    stateTaux: [],
    stateOrdrePaiement: [],
    stateActiviteSurOP: [],
    stateListeOPParUser: [],
    stateFacture: [],
     stateOpParActivite:[],
      stateActiviteglobal: [],
  stateListeOPgloba: [],
    stateAfficheBudgetVise: [],
    stateBanque: [],
    stateCompteBancaire: [],
    stateInfoOrdrePaiement: [],
    stateFactureParOp: [],
    stateBudgetEclateMod: [],
    stateBudgetModifierEnProjet: [],
    stateSignataire: [],
    stateSecteurActivite: [],
    stateRegimeImpossition: [],
    stateFormeJuridique: [],
    stateOpPersonnel: [],
    stateOpPersonnelParUser:[]
    // stateAfficheDotation:[]

};

export default defaultstate